name: Deploy to Contabo Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Contabo server to known_hosts
        run: |
          ssh-keyscan 37.60.230.124 >> ~/.ssh/known_hosts

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure Node.js 18 is used for compatibility

      # Clean npm cache and reinstall dependencies
      - name: Clean environment
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Verify dependency tree to check for conflicts
      - name: Check dependency tree
        run: npm ls || true

      - name: Build Strapi project
        run: npm run build --debug

      # Deploy the build to the Contabo server
      - name: Deploy to server
        run: |
          ssh root@37.60.230.124 "
          cd /var/www/green-public &&
          git pull origin main &&
          npm install --legacy-peer-deps &&
          npm run build &&
          pm2 restart strapi"
