name: Deploy Strapi to Contabo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Or the version you need for your project

      - name: Install dependencies
        run: npm install

      - name: Build Strapi
        run: npm run build

      - name: Deploy to Contabo Server
        run: |
          ssh root@37.60.230.124 "
          cd /var/www/green-public &&
          git pull origin main &&
          npm install &&
          npm run build &&
          pm2 restart strapi"
