name: Deploy to Contabo Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Contabo server to known_hosts
        run: |
          ssh-keyscan 37.60.230.124 >> ~/.ssh/known_hosts

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you need

      # Clean npm cache before installing
      - name: Clean npm cache
        run: npm cache clean --force

      # Remove node_modules and package-lock.json to ensure a clean install
      - name: Clean npm modules
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      # Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Build Strapi project
        run: npm run build

      - name: Deploy to server
        run: |
          ssh root@37.60.230.124 "
          cd /var/www/green-public &&
          git pull origin main &&
          npm install &&
          npm run build &&
          pm2 restart strapi"
