name: Deploy to Contabo Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Or whichever version of Node.js is required by your project

      - name: Clean and install dependencies
        run: |
          rm -rf node_modules
          npm ci  # This ensures a clean install from package-lock.json

      - name: Build Strapi project
        run: npm run build

      - name: Deploy to server
        run: |
          ssh root@37.60.230.124 "
          cd /var/www/green-public &&
          git pull origin main &&
          npm ci &&
          npm run build &&
          pm2 restart strapi"  # Update to use your PM2 process name: strapi
